[project]
name = "reddit-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "cuda", email = "lansaramine705@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
reddit-app = "reddit_app:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
